FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
    DOTNET_NOLOGO=1 \
    NUGET_XMLDOC_MODE=skip

COPY ./ ./

RUN dotnet restore ./todo2.IntegrationTests/todo2.IntegrationTests.csproj

CMD ["dotnet", "test", "./todo2.IntegrationTests/todo2.IntegrationTests.csproj", "-c", "Release", "--logger", "trx;LogFileName=test_results.trx"]